const Review = require("../models/Review");

module.exports.getReviewData = async (req, res) => {
  try {
    const review = await Review.find({});
    res.status(200).json({ status: "success", data: review });
  } catch (err) {
    res.status(422).json({
      status: "failed ðŸ”´",
      message: err,
    });
  }
};

module.exports.getReviewById = async (req, res) => {
  try {
    const review = await Review.findById(req.params.id);
    if (!review) {
      return `Review Id: ${req.params._id} not found!`;
    }
    res.status(200).json({
      status: "success",
      data: review,
    });
  } catch (err) {
    res.status(422).json({
      status: "failed ðŸ”´",
      message: err,
    });
  }
};

module.exports.createReview = async (req, res) => {
  try {
    const review = await Review.create(req.body);
    res.status(200).json({
      status: "success",
      data: {
        review,
      },
    });
  } catch (err) {
    res.status(422).json({
      status: "failed ðŸ”´",
      message: err,
    });
  }
};

module.exports.updateReview = async (req, res) => {
  try {
    const review = await Review.findByIdAndUpdate(req.params.id, req.body, {
      new: true, // Return the updated document
      runValidators: true, // Validate the data before updating
    });
    if (!Review) {
      return `Review Id: ${req.params.id} not found!`;
    }
    res.status(200).json({
      status: "success",
      data: review,
    });
  } catch (err) {
    res.status(422).json({
      status: "failed ðŸ”´",
      message: err,
    });
  }
};

module.exports.deleteReview = async (req, res) => {
  try {
    const review = await Review.findByIdAndDelete(req.params.id);
    if (!review) {
      return `Review Id: ${req.params.id} not found!`;
    }
    res.status(200).json({
      status: "success",
      message: "data deleted successfully",
    });
  } catch (err) {
    res.status(422).json({
      status: "failed ðŸ”´",
      message: err,
    });
  }
};
